// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAALT77ywMSBwh9cLfdtCYAW0dyCzeN_Fk',
    appId: '1:158632156130:web:d3a9e887b4aacab64e37bb',
    messagingSenderId: '158632156130',
    projectId: 'plant-app-282e0',
    authDomain: 'plant-app-282e0.firebaseapp.com',
    storageBucket: 'plant-app-282e0.appspot.com',
    measurementId: 'G-5L67WD09LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD67iRqTTrD9KOyXYtcpUHd3JXj5oTOn1o',
    appId: '1:158632156130:android:bc9713dd97e72ece4e37bb',
    messagingSenderId: '158632156130',
    projectId: 'plant-app-282e0',
    storageBucket: 'plant-app-282e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfi5tGu3c2WO04m_u0qMLRfTBztvjTb_U',
    appId: '1:158632156130:ios:ae4db15bc3195c7e4e37bb',
    messagingSenderId: '158632156130',
    projectId: 'plant-app-282e0',
    storageBucket: 'plant-app-282e0.appspot.com',
    iosClientId: '158632156130-k0ss89833s8em76tscderujf54403j3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.individualproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfi5tGu3c2WO04m_u0qMLRfTBztvjTb_U',
    appId: '1:158632156130:ios:ae4db15bc3195c7e4e37bb',
    messagingSenderId: '158632156130',
    projectId: 'plant-app-282e0',
    storageBucket: 'plant-app-282e0.appspot.com',
    iosClientId: '158632156130-k0ss89833s8em76tscderujf54403j3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.individualproject',
  );
}
